INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (1, '北京市', '北京', 101010, 'beijing');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (2, '上海市', '上海', 101020, 'shanghai');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (3, '天津市', '天津 ', 101030, 'tianjing');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (4, '重庆市', '重庆', 101040, 'chongqin');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (5, '黑龙江省 ', '哈尔滨 ', 101050, 'haerbin');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (6, '吉林省', '长春', 101060, 'changchun');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (7, '辽宁省', '沈阳', 101070, 'shenyang');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (8, '内蒙古自治区', '呼和浩特', 101080, 'huhehaote');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (9, '河北省', '石家庄', 101090, 'shijiazhuang');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (10, '新疆维吾尔自治区', '乌鲁木齐', 101100, 'wulumuqi');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (11, '甘肃省', '兰州', 101110, 'lanzhou');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (12, '青海省', '西宁', 101120, 'xining');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (13, '陕西省', '西安', 101140, 'xian');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (14, '宁夏回族自治区', '银川', 101130, 'yinchuan');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (15, '河南省', '郑州', 101150, 'zhengzhou');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (16, '山东省', '济南', 101160, 'jinan');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (17, '山西省', '太原', 101170, 'taiyuan');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (18, '安徽省', '合肥', 101180, 'hefei');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (19, '湖南省', '长沙', 101190, 'changsha');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (20, '湖北省', '武汉', 101200, 'wuhan');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (21, '江苏省', '南京', 101210, 'nanjing');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (22, '四川省', '成都', 101220, 'chengdu');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (23, '贵州省', '贵阳', 101230, 'guiyang');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (24, '云南省', '昆明', 101240, 'kunming');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (25, '广西壮族自治区', '南宁', 101250, 'nanning');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (26, '西藏自治区', '拉萨', 101260, 'lasa');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (27, '浙江省', '杭州', 101270, 'hangzhou');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (28, '江西省', '南昌', 101280, 'nanchang');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (29, '广东省', '广州 ', 101290, 'guangzhou');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (30, '福建省', '福州', 101300, 'fuzhou');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (31, '台湾省', '台北', 101310, 'taibei');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (32, '海南省', '海口', 101320, 'haikou');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (33, '香港特别行政区', '香港', 101330, 'xianggang');
INSERT INTO `weather` (`id`, `provice`, `city`, `number`, `Ename`) VALUES (34, '澳门特别行政区', '澳门', 101340, 'aomen');
